### ISSUE TITLE
Error reading sketches: file is corrupted (mismatched file names)

### ISSUE THREAD

**Issue by standage** [will-rowe/hulk#3]
I've sketched a few read sets and want to try some of the other operations, namely print and distance. Whenever I attempt to invoke either of these operations, I get the following error message.

```
encountered error: file is corrupted (mismatched file names): sample1-k21.sketch
```

If I invoke the command without the `.sketch` extension then I just get a file not found error, so that doesn't seem to be the problem.

Does anything about the following commands look reveal a mistake on my part? Or is this potentially a software issue?

```
hulk sketch --fastq seq/sample1.fastq -k 21 -o sketches/sample1-k21 -p 4
hulk sketch --fastq seq/sample2.fastq -k 21 -o sketches/sample2-k21 -p 4
hulk print -f sketches/sample1-k21.sketch
hulk distance -1 sketches/sample1-k21.sketch -2 sketches/sample2-k21.sketch
```

I'm running hulk 0.0.2 installed via conda on CentOS 6.

**Comment by will-rowe** [comment]
I’ve recreated this - it’s a software issue! I think it is because of the way the sketches store the metadata from the fastqs, which in your case were in a sub dir (which I never included in my tests... as I usually pipe in a data stream). I will fix this mistake - which is a silly one and I’m sorry for the inconvenience it cause you. A quick fix would be for you to just pipe the fastq into the hulk sketchcommand, but I will let you know when I fix this properly in the next day or so!

**Comment by will-rowe** [comment]
I've just fixed this - it was an unnecessary check anyway so have just removed it (8828bd6499da0eb35f7567a3b40ebba963db1d9b). I will prepare a new release and conda recipe soon - there are a few other changes I would like to make first.

**Comment by will-rowe** [comment]
Thanks again for pointing this out @standage - closing this now.
